app.py
from flask import Flask
from routes.routes import bp
app = Flask(__name__)

app.register_blueprint(bp)



if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

routes/routes.py
import click
from flask import Blueprint, request, render_template, jsonify
from database.database import DB

# Se crea una instancia de Blueprint para poder crear rutas
bp = Blueprint('routes', __name__)

# Se crea una instancia de la base de datos
db = DB()


# Ruta para mostrar los items de la base de datos
@bp.route('/items', methods=['GET'])
def get_all_items():
    return db.get_all_items()


# Ruta para agregar un item a la base de datos
@bp.route('/add_items', methods=['POST'])
def add_item():
    name = request.json['name']
    sell_in = request.json['sell_in']
    quality = request.json['quality']
    type = request.json['type']
    return db.add_item(name, sell_in, quality, type)


# Ruta para actualizar un item del inventario
@bp.route('/update_item', methods=['PUT'])
def update_item():
    item_id = request.json['_id']
    name = request.json['name']
    sell_in = request.json['sell_in']
    quality = request.json['quality']
    return db.update_item(item_id, name, sell_in, quality)


# Ruta para mostrar un item
@bp.route('/item/<item_id>', methods=['GET'])
def get_item(item_id):
    return db.get_item(item_id)


# Ruta para inicializar la base de datos
@bp.route('/inicializar', methods=['POST'])
def init_db():
    return db.init_db()


@bp.route('/delete_item', methods=['DELETE'])
def delete_item():
    item_id = request.json['_id']
    return db.delete_item(item_id)


@bp.route('/get_inventory', methods=['GET'])
def get_inventory():
    return db.get_inventory()


@bp.route('/update_inventory', methods=['PUT'])
def update_inventory():
    return db.update_inventory()


@bp.route('/delete_many', methods=['DELETE'])
def delete_many_items():
    type = request.json.get('type')
    return db.delete_many_items(type)


@bp.route('/form/all_items', methods=['GET'])
def all_items_html():
    return render_template('all_items_temp.html', items=db.get_all_items().json['result'])


@bp.route('/form/update', methods=['POST', 'GET'])
def update_html():
    if request.method == 'POST':
        _id = request.form['_id']
        name = request.form['name']
        sell_in = request.form['sell_in']
        quality = request.form['quality']
        return db.update_item(_id, name, sell_in, quality)

    else:
        return render_template('update_item_temp.html')


@bp.route('/form/create', methods=['POST', 'GET'])
def create_html():
    if request.method == 'POST':
        name = request.form['name']
        sell_in = request.form['sell_in']
        quality = request.form['quality']
        item_type = request.form['type']
        _id = db.add_item(name, sell_in, quality, item_type).json['result']['_id']

        return render_template('create_item_temp.html', datosItem=db.get_item(_id).json['result'])

    else:
        return render_template('create_item_temp.html', datosItem='')

templates/all_items_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List items</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='tabla.css') }}">
</head>
<body>
    <h1>Inventory</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Quality</th>
            <th>Sell in</th>
            <th>Type</th>
        </tr>
          {% for item in items %}
              <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.quality }}</td>
                <td>{{ item.sell_in }}</td>
                <td>{{ item.type }}</td>
              </tr>
          {% endfor %}
    </table>

</body>
</html>

templates/create_item_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Item</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <form method="POST" action="{{ url_for('routes.create_html') }}">
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" required>
        <label for="sell_in">Sell in</label>
        <input type="text" id="sell_in" name="sell_in" required>
        <label for="quality">Quality</label>
        <input type="text" id="quality" name="quality" required>
        <label for="type">Type</label>
        <select type="text" id="type" name="type" required>
            <option value="normal">Normal</option>
            <option value="sulfuras">Sulfuras</option>
            <option value="conjured">Conjured</option>
            <option value="backstage">Backstage</option>
            <option value="aged brie">Aged Brie</option>
        </select>
        <input type="submit" value="Enviar">
    </form>
    {% if datosItem != '' %}
            <table>
              <tr>
                <td> ID: {{ datosItem._id}}</td>
                <td>Name: {{  datosItem.name}}</td>
                <td>Sell in: {{  datosItem.sell_in }}</td>
                <td>Quality: {{  datosItem.quality }}</td>
                <td>Type: {{  datosItem.type }}</td>
              </tr>
            </table>
    {% else %}
    {% endif %}


</body>
</html>

templates/update_item_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Item</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>Update Item</h1>
    <form method="POST" action="{{ url_for('routes.update_html') }}">
        <label for="_id">_id</label>
        <input type="text" id="_id" name="_id" required>
        <label for="name">Nombre:</label>
        <input type="text" id="name" name="name" required>
        <label for="sell_in">Sell in</label>
        <input type="text" id="sell_in" name="sell_in" required>
        <label for="quality">Quality</label>
        <input type="text" id="quality" name="quality" required>
        <input type="submit" value="Enviar">
    </form>

</body>
</html>